@ui
Feature: Delivery instructions (optional)

  Background:
    Given I have "Signature Cherry Lattice" in my cart with quantity 1
    And I am on the checkout page

  Scenario: Character counter updates as instructions are typed
    When I enter a short random delivery instruction
    Then the character counter should show the correct count

  Scenario: Random instructions generated by Faker stay within the limit
    When I enter random delivery instructions
    Then the character counter should be within the 200-character limit
    And no character limit warning should be shown

  Scenario: Instructions exceeding 200 characters show a warning
    When I enter delivery instructions that exceed the character limit
    Then the character counter should show more than 200 characters used
    And I should see a character limit warning
